version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
  pre_build:
    commands:
      - mkdir build
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t band .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Running tests, linter and codecov
      - docker run --rm band flake8
      - docker run --rm -v $(pwd)/build:/usr/src/app/build band pytest --cov --cov-report xml
      - codecov --token $CODECOV_TOKEN --file build/coverage.xml
